# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('applications', ['internet', 'config-store', 'stats'])
    module.use.append('DASH')
    module.source = [
        'model/bulk-send-application.cc',
        'model/onoff-application.cc',
        'model/packet-sink.cc',
        'model/udp-client.cc',
        'model/udp-server.cc',
        'model/seq-ts-header.cc',
        'model/udp-trace-client.cc',
        'model/packet-loss-counter.cc',
        'model/udp-echo-client.cc',
        'model/udp-echo-server.cc',
        'model/application-packet-probe.cc',
        'model/dash-fake-server.cc',
        'model/http-server.cc',
        'model/node-throughput-tracer.cc',
        'model/http-server-fake-clientsocket.cc',
        'model/http-server-fake-virtual-clientsocket.cc',
        'model/http-client.cc',
        'model/http-client-dash.cc',
        'model/http-multimedia-consumer.cc',
        'model/dashplayer-tracer.cc',
        'model/three-gpp-http-client.cc',
        'model/three-gpp-http-server.cc',
        'model/three-gpp-http-header.cc',
        'model/three-gpp-http-variables.cc',
        'helper/bulk-send-helper.cc',
        'helper/on-off-helper.cc',
        'helper/packet-sink-helper.cc',
        'helper/udp-client-server-helper.cc',
        'helper/udp-echo-helper.cc',
        'helper/three-gpp-http-helper.cc',
        'helper/http-helper.cc',
        'helper/dash-http-client-helper.cc',
        'helper/dash-server-helper.cc',
        'model/gta-dash.cc',
        'model/aggregation.cc',
        'helper/aggregation-helper.cc',
        'model/dash-fake-cache-server.cc',
        'model/dash-fake-virtual-clientsocket.cc',
        'helper/dash-cache-server-helper.cc',
        'model/edge-dash-fake-server.cc',
        'helper/edge-dash-server-helper.cc',
        'model/monitoring.cc',
        'model/ctrl-main.cc',
        'model/bigtable.cc'
        ]

    applications_test = bld.create_ns3_module_test_library('applications')
    applications_test.source = [
        'test/three-gpp-http-client-server-test.cc',
        'test/udp-client-server-test.cc'
        ]

    headers = bld(features='ns3header')
    headers.module = 'applications'
    headers.source = [
        'model/bulk-send-application.h',
        'model/onoff-application.h',
        'model/packet-sink.h',
        'model/udp-client.h',
        'model/udp-server.h',
        'model/seq-ts-header.h',
        'model/udp-trace-client.h',
        'model/packet-loss-counter.h',
        'model/udp-echo-client.h',
        'model/udp-echo-server.h',
        'model/application-packet-probe.h',
        'model/dash-fake-server.h',
        'model/http-server.h',
        'model/node-throughput-tracer.h',
        'model/http-server-fake-clientsocket.h',
        'model/http-server-fake-virtual-clientsocket.h',
        'model/http-client.h',
        'model/http-client-dash.h',
        'model/http-multimedia-consumer.h',
        'model/dashplayer-tracer.h',
        'model/three-gpp-http-client.h',
        'model/three-gpp-http-server.h',
        'model/three-gpp-http-header.h',
        'model/three-gpp-http-variables.h',
        'helper/bulk-send-helper.h',
        'helper/on-off-helper.h',
        'helper/packet-sink-helper.h',
        'helper/udp-client-server-helper.h',
        'helper/udp-echo-helper.h',
        'helper/three-gpp-http-helper.h',
        'helper/http-helper.h',
        'helper/dash-http-client-helper.h',
        'helper/dash-server-helper.h',
        'model/gta-dash.h',
        'model/aggregation.h',
        'helper/aggregation-helper.h',
        'model/dash-fake-cache-server.h',
        'model/dash-fake-virtual-clientsocket.h',
        'helper/dash-cache-server-helper.h',
        'model/edge-dash-fake-server.h',
        'helper/edge-dash-server-helper.h',
        'model/monitoring.h',
        'model/ctrl-main.h',
        'model/bigtable.h',
        'model/group-user.h',
        'model/path.h',
        'model/network-graph.h'
        ]

    if (bld.env['ENABLE_EXAMPLES']):
        bld.recurse('examples')

    bld.ns3_python_bindings()
